package kv3

const (
	DATA_TYPE_NULL         = 0x01
	DATA_TYPE_BOOL         = 0x02
	DATA_TYPE_INT64        = 0x03
	DATA_TYPE_UINT64       = 0x04
	DATA_TYPE_DOUBLE       = 0x05
	DATA_TYPE_STRING       = 0x06
	DATA_TYPE_BLOB         = 0x07
	DATA_TYPE_ARRAY        = 0x08
	DATA_TYPE_OBJECT       = 0x09
	DATA_TYPE_TYPED_ARRAY  = 0x0A
	DATA_TYPE_INT32        = 0x0B
	DATA_TYPE_UINT32       = 0x0C
	DATA_TYPE_TRUE         = 0x0D
	DATA_TYPE_FALSE        = 0x0E
	DATA_TYPE_INT_ZERO     = 0x0F
	DATA_TYPE_INT_ONE      = 0x10
	DATA_TYPE_DOUBLE_ZERO  = 0x11
	DATA_TYPE_DOUBLE_ONE   = 0x12
	DATA_TYPE_FLOAT        = 0x13
	DATA_TYPE_BYTE         = 0x17
	DATA_TYPE_TYPED_ARRAY2 = 0x18
	DATA_TYPE_RESOURCE     = 0x86
)
